connect:
  twitter:
    key: "my_key"
    secret: "my_secret"
    label: "Twitter"
  facebook:
    key: "my_key"
    secret: "my_secret"
    label: "Facebook"
  google:
    key: "my_key"
    secret: "my_secret"
    label: "Google"
  yahoo:
    key: "my_key"
    secret: "my_secret"
    label: "Yahoo"